baseURL = 'https://github.com/isherwood-sec/portfolio/home.md'
languageCode = 'en-us'
title = 'Anthony Isherwood'
theme = "m10c"


[params]
  author = "Anthony Isherwood"
  description = "Cyber Security expertise for individuals and businesses."
  menu_item_separator = " - "
  # avatar = "/static/IsherwoodA.JPG"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/isherwood-sec"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/anthonyisherwood/"
  [[params.social]]
    icon = "mail"
    name = "E-Mail"
    url = "mailto:isherwoodsec@fastmail.com"

