baseURL = 'home.md'
languageCode = 'en-us'
title = 'Anthony Isherwood'
theme = "hermit"

[params]
  author = "Anthony Isherwood"
  description = "Cyber Security expertise for individuals and businesses."
